# Generated by Django 2.2 on 2022-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_auto_20220122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='occup',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
